### ISSUE TITLE
YellowBotWebViewActivity.kt line 25 (com.yellowmessenger.ymchat.YellowBotWebViewActivity.onBackPressed)

### ISSUE THREAD

**Issue by shrikant-zolve** [yellowmessenger/YMChatbot-Android#74]
Fatal Exception: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1996)
       at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:661)
       at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:436)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:255)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:673)
       at com.yellowmessenger.ymchat.YellowBotWebViewActivity.onBackPressed(YellowBotWebViewActivity.kt:25)
       at com.yellowmessenger.ymchat.YellowBotWebviewFragment.onStart(YellowBotWebviewFragment.kt:851)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
       at android.app.Activity.performStart(Activity.java:8226)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3796)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2318)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8295)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by sukrit-ym** [comment]
Hi Shrikant

Thanks for reporting, we will handle this in our upcoming release.

**Comment by shrikant-zolve** [comment]
Thanks

**Comment by sukrit-ym** [comment]
@shrikant-zolve We have release a new version v2.3.2 which should solve the problem
